# $FreeBSD$

#./iwlwifi-7260-7.ucode
#./iwlwifi-7260-8.ucode
#./iwlwifi-7260-9.ucode
#./iwlwifi-7265-8.ucode
#./iwlwifi-7265-9.ucode

KMOD=	iwn7260_7fw
IMG=	iwlwifi-7260-7.ucode

.include <bsd.kmod.mk>
